---
title: "hospital_data"
output: html_document
---

```{r}
library(tidyverse)
library(haven)
```


```{r}
hospital_data =
  read_csv(file = "./data/Hospitals.csv") %>% 
  rename(location_1 = `Location 1`)
  tibble(
    location_1 = c("413 120th Street New York, NY 10035 (40.798205044469, -73.932667945174)", "79 01 Elmhurst, NY 11373 (40.738710402563, -73.878351155182)", "	2201 Neptune Avenue Brooklyn, NY 11224 (40.578488319967, -73.989497148121)"))
  
  hospital_data <- hospital_data %>% 
    mutate(
      latitude = as.numeric(str_extract(location_1, "(?<=\\()[^,]+")),
      longitude = as.numeric(str_extract(location_1, "(?<=, ).+?(?=\\))"))
    )
    
  
head(hospital_data)

facilities_by_borough = 
  hospital_data %>%
  group_by(Borough) %>%
  summarise(Facility_Count = n())

hospitals_by_type = 
  hospital_data %>% 
  group_by(`Facility Type`) %>% 
  summarise(Facility_Count = n())

facility_type_by_borough =
  hospital_data %>%
  group_by(Borough, `Facility Type`) %>%
  summarise(Facility_Count = n(), .groups = "drop") %>%
  pivot_wider(names_from = `Facility Type`, values_from = Facility_Count, values_fill = 0)

ggplot(data = facilities_by_borough, aes(x = Borough, y = Facility_Count, fill = Borough)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of Facilities by Borough", x = "Borough", y = "Facility Count")

```

