---
title: "interactive_map"
output: html_document
---
<details> <summary>Code</summary>
```{r}
hospital_data =
  read_csv(file = "./data/Hospitals.csv") %>% 
  rename(location_1 = `Location 1`, 
         facility_type = `Facility Type`,
         facility_name = `Facility Name`)
  tibble(
    location_1 = c("413 120th Street New York, NY 10035 (40.798205044469, -73.932667945174)", "79 01 Elmhurst, NY 11373 (40.738710402563, -73.878351155182)", "	2201 Neptune Avenue Brooklyn, NY 11224 (40.578488319967, -73.989497148121)"))
  
  hospital_data <- hospital_data %>% 
    mutate(
      latitude = as.numeric(str_extract(location_1, "(?<=\\()[^,]+")),
      longitude = as.numeric(str_extract(location_1, "(?<=, ).+?(?=\\))"))
    )
    
  
head(hospital_data)
```
</details>

<details> <summary>Code</summary>
```{r}
library(leaflet)
library(dplyr)

hospital_map <- leaflet(hospital_data) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(
    lat = ~latitude,
    lng = ~longitude,
    radius = 6,
    color = ~case_when(
      Borough == "Manhattan" ~ "blue",
      Borough == "Queens" ~ "green",
      Borough == "Brooklyn" ~ "purple",
      Borough == "Bronx" ~ "red",
      Borough == "Staten Island" ~ "orange",
      TRUE ~ "gray"
    ),
    stroke = FALSE,
    fillOpacity = 0.7,
    popup = ~paste(
      "<b>Facility Name:</b> ", facility_name, "<br>",
      "<b>Facility Type:</b> ", facility_type, "<br>",
      "<b>Borough:</b> ", Borough, "<br>",
      "<b>Phone:</b> ", Phone
    ),
    group = ~Borough
  ) %>%
  addLayersControl(
    overlayGroups = c("Manhattan", "Queens", "Brooklyn", "Bronx", "Staten Island"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  setView(lng = -73.935242, lat = 40.730610, zoom = 10)

hospital_map



```
</details>

```{r, echo = FALSE}
hospital_map
```

