---
title: "projectdraft"
output: html_document
date: "2024-11-18"
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(haven)
library(readr)
```

# Lisa: ADD Health Data 
```{r}
library(haven)
library(janitor)
library(dplyr)
library(knitr)


w1data <- read.csv("w1inhome.csv") %>%
  clean_names() %>% 
  select(aid, h1gi14, h1gi11, h1gi12, h1gi13m, h1gi4, h1gi8, h1nm6, h1nf6) 

w4data <- read_sas("w4inhome.sas7bdat") %>% 
  clean_names() %>% 
  mutate(
    across(everything(), ~ type.convert(as.character(.), as.is = TRUE)),
    first_gen = case_when(
      h4od4 == 0 ~ 1, 
      h4od4 == 1 ~ 0, 
      TRUE ~ NA_real_
    )
  )

first_gen_count <- w4data %>% 
  count(first_gen, name = "count")
print(first_gen_count)

merged_df <- w1data %>%
  inner_join(w4data, by = "aid") %>% 
  mutate(
    first_generation = case_when(
      h4od4 == 0 | h1gi11 == 0 ~ 1, 
      TRUE ~ 0
    ),
    second_generation = case_when(
      h1nm6 == 0 | h1nf6 == 0 ~ 1, 
      TRUE ~ 0
    ), 
    third_generation = case_when(
      first_generation == 0 & second_generation == 0 ~ 1, 
      TRUE ~ 0 
    )
  )

generation_counts <- merged_df %>% 
  summarize(
     first_generation = sum(first_generation, na.rm = TRUE),
    second_generation = sum(second_generation, na.rm = TRUE),
    third_generation = sum(third_generation, na.rm = TRUE)
  ) %>%
  pivot_longer(everything(), names_to = "Generation", values_to = "Count")

generation_counts %>% 
  kable(
    caption = "Individuals by Generation Status",
    col.names = c("Generation Status", "Count"), 
    align = "lc",
    format = "markdown"
  )
  
```

creating tables & visualizations of the following health indicators by immigrant generation status: blood pressure classification, high cholesterol, and body mass index classification

first, cleaning the data for each of the health indicators 
```{r}
filtered_df <- merged_df %>%
  mutate(across(
    c(h4bpcls, h4id5b, h4bmicls),
    ~ replace(., 
              (cur_column() == "h4bpcls" & (h4bpcls == 6 | h4bpcls == 7 | h4bpcls == 9)) |
              (cur_column() == "h4id5b" & (h4id5b == 6 | h4id5b == 8)) |
              (cur_column() == "h4bmicls" & (h4bmicls == 88 | h4bmicls == 89 | h4bmicls == 96 | h4bmicls == 97 | h4bmicls == 99)),
              NA)
  )) %>%
  drop_na(h4bpcls, h4id5b, h4bmicls)


bp_table <- filtered_df %>%
  count(h4bpcls, first_generation, second_generation, third_generation) %>%
  filter(!(h4bpcls == 6 | h4bpcls == 7 | h4bpcls == 9)) %>%
  mutate(
    h4bpcls = recode(h4bpcls,
                     `1` = "Normal",
                     `2` = "Prehypertension",
                     `3` = "Hypertension I",
                     `4` = "Hypertension II")
  ) %>%
  pivot_wider(
    names_from = c("first_generation", "second_generation", "third_generation"),
    values_from = n,
    values_fill = list(n = 0)
  ) %>%
  rename(
    `First Generation` = `1_0_0`,
    `Second Generation` = `0_1_0`,  
    `Third Generation` = `0_0_1`    
  ) %>%
  select(h4bpcls, `First Generation`, `Second Generation`, `Third Generation`)

bp_table %>% 
  kable(caption = "Blood Pressure Classification by Immigrant Generation Status", format = "html")

bp_first_gen <- bp_table %>%
  pivot_longer(cols = c(`First Generation`), 
               names_to = "Generation", 
               values_to = "Count") %>%
  filter(Generation == "First Generation")  


bp_first_gen_plot <- bp_first_gen %>%
  ggplot(aes(x = h4bpcls, y = Count, fill = h4bpcls)) +
  geom_bar(stat = "identity", width = 0.6) +
  labs(
    title = "Blood Pressure Classification for First Generation Immigrants",
    x = "Blood Pressure Classification",
    y = "Count",
    fill = "Blood Pressure"
  ) +
  scale_x_discrete(labels = c("Normal", "Prehypertension", "Hypertension I", "Hypertension II")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "none"  
  )

bp_first_gen_plot

```


High Blood Cholesterol 

```{r}

cholesterol_table <- filtered_df %>% 
  count(h4id5b, first_generation, second_generation, third_generation) %>% 
  filter(!(h4id5b == 6 | h4id5b == 8)) %>% 
  mutate(
    h4id5b = recode(h4id5b, 
                    `0` = "No", 
                    `1` = "Yes")
  ) %>%
  pivot_wider(
    names_from = c("first_generation", "second_generation", "third_generation"),
    values_from = n,
    values_fill = list(n = 0)
  ) %>%
  rename(
    `First Generation` = `1_0_0`,
    `Second Generation` = `0_1_0`,  
    `Third Generation` = `0_0_1`    
  ) %>%
  select(h4id5b, `First Generation`, `Second Generation`, `Third Generation`)

cholesterol_table %>% 
  kable(caption = "Blood Cholesterol Classification by Immigrant Generation Status", format = "html")


cholesterol_first_gen <- cholesterol_table %>%
  pivot_longer(cols = c(`First Generation`), 
               names_to = "Generation", 
               values_to = "Count") %>%
  filter(Generation == "First Generation")  


cholesterol_first_gen_plot <- cholesterol_first_gen %>%
  ggplot(aes(x = h4id5b, y = Count, fill = h4id5b)) +
  geom_bar(stat = "identity", width = 0.6) +
  labs(
    title = "Blood Cholesterol Classification for First Generation Immigrants",
    x = "Blood Cholesterol Classification",
    y = "Count",
    fill = "Blood Cholesterol"
  ) +
  scale_x_discrete(labels = c("No", "Yes")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "none"  
  )

cholesterol_first_gen_plot
```

Body Mass Index 
```{r}
bmi_table <- filtered_df %>% 
  count(h4bmicls, first_generation, second_generation, third_generation) %>% 
  filter(!(h4bmicls == 88 | h4bmicls == 89 | h4bmicls == 96 | h4bmicls == 97 | h4bmicls == 99)) %>% 
  mutate(
    h4bmicls = recode(h4bmicls, 
                    `1` = "Underweight <18.5", 
                    `2` = "Normal 18.5 - < 25", 
                    `3` = "Overweight 25 - <30", 
                    `4` = "Obese I 30-<35", 
                    `5` = "Obese II: 35-<40", 
                    `6` = "Obese III: 40+",
                    )
  ) %>%
  pivot_wider(
    names_from = c("first_generation", "second_generation", "third_generation"),
    values_from = n,
    values_fill = list(n = 0)
  ) %>%
  rename(
    `First Generation` = `1_0_0`,
    `Second Generation` = `0_1_0`,  
    `Third Generation` = `0_0_1`    
  ) %>%
  select(h4bmicls, `First Generation`, `Second Generation`, `Third Generation`)

bmi_table %>% 
  kable(caption = "Blood Cholesterol Classification by Immigrant Generation Status", format = "html")


bmi_first_gen <- bmi_table %>%
  pivot_longer(cols = c(`First Generation`), 
               names_to = "Generation", 
               values_to = "Count") %>%
  filter(Generation == "First Generation")  


bmi_first_gen_plot <- bmi_first_gen %>%
  ggplot(aes(x = h4bmicls, y = Count, fill = h4bmicls)) +
  geom_bar(stat = "identity", width = 0.6) +
  labs(
    title = "BMI Classification for First Generation Immigrants",
    x = "BMI Classification",
    y = "Count",
    fill = "BMI"
  ) +
  scale_x_discrete(labels = c("Underweight <18.5", "Normal 18.5 - < 25", "Overweight 25 - <30","Obese I 30-<35", "Obese II: 35-<40","Obese III: 40+" )) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "none"  
  )

bmi_first_gen_plot
```

# Nasiha: Hospital Data 

```{r}
hospital_data =
  read_csv(file = "./data/Hospitals.csv")

facilities_by_borough = 
  hospital_data %>%
  group_by(Borough) %>%
  summarise(Facility_Count = n())

hospitals_by_type = 
  hospital_data %>% 
  group_by(`Facility Type`) %>% 
  summarise(Facility_Count = n())

facility_type_by_borough =
  hospital_data %>%
  group_by(Borough, `Facility Type`) %>%
  summarise(Facility_Count = n(), .groups = "drop") %>%
  pivot_wider(names_from = `Facility Type`, values_from = Facility_Count, values_fill = 0)

ggplot(data = facilities_by_borough, aes(x = Borough, y = Facility_Count, fill = Borough)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of Facilities by Borough", x = "Borough", y = "Facility Count")



```

# Yucheng: Shelter Data 

```{r}
as_df = read_csv("./data/asylum_seekers_report.csv") |> 
  janitor::clean_names() |> 
  filter(agency != "total") |> 
  mutate(category = ifelse(category == "Population - Individuals", "Individuals", category))

head(as_df)
```
```{r}
count_by_cat = as_df |> 
  group_by(category) |> 
  summarize(count_by_cat = sum(count, na.rm = TRUE), .groups = "drop")

ggplot(count_by_cat, aes(x = category, y = count_by_cat, fill = category)) +
  geom_col() +
  labs(title = "Total Counts of Asylum Seekers by Category", x = "Category", y = "Count") +
  scale_fill_viridis_d() +
  theme_minimal()
```
```{r}
counts_by_cat_agen = 
  ggplot(as_df, aes(x = category, y = count, fill = agency)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Counts by Category and Agency", x = "Category", y = "Count") +
  scale_fill_viridis_d() +
  theme_minimal()

ggplotly(counts_by_cat_agen)
```
