---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(viridis)
library(lubridate)
library(rsconnect)
library(leaflet)
library(stringr)
library(readr)

```

```{r}
daily_df = read_csv("./data/dhs_daily_report.csv", na = "NA") |> 
  filter(count != "NA") |> 
  mutate(
    year = year(date),
    month = month(date),
    day = day(date)
  )


hospital_data <- read_csv(file = "./data/Hospitals.csv") |>  
  rename(
    location_1 = `Location 1`, 
    facility_type = `Facility Type`,
    facility_name = `Facility Name`
  ) |> 
  mutate(
    latitude = as.numeric(str_extract(location_1, "(?<=\\()[^,]+")),
    longitude = as.numeric(str_extract(location_1, "(?<=, ).+?(?=\\))"))
  )


```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(
  inputId = "time_units",
  label = h3("Select Time Units for Trends"),
  choices = c("Overall Trends by Date" = "date", "Monthly Trends" = "month", "Daily Trends" = "day"),
  selected = "date"
)
```

```{r}
checkboxGroupInput(
  inputId = "boroughs",
  label = h3("Select Borough(s):"),
  choices = c("Manhattan", "Queens", "Brooklyn", "Bronx", "Staten Island"),
  selected = c("Manhattan", "Queens", "Brooklyn", "Bronx", "Staten Island")
)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Trends of the Number of Asylum Seekers in Shelters

```{r}
renderPlotly({
  filtered_df <- daily_df |> filter(measure == "Total Individuals")
  
  if (input$time_units == "date") {
    plot <- ggplot(filtered_df, aes(x = date, y = count)) +
      geom_line(color = "blue") +
      labs(
        title = "Total Individuals in Shelter Over Time",
        x = "Date",
        y = "Number of Individuals"
      ) +
      theme_minimal()
    
  } else if (input$time_units == "month") {
    monthly_df <- filtered_df |> 
      group_by(month) |> 
      summarise(total_count = sum(count, na.rm = TRUE), .groups = "drop")
    
    plot <- ggplot(monthly_df, aes(x = month, y = total_count)) +
      geom_line(color = "red", size = 1) +
      labs(
        title = "Monthly Trends in Total Individuals",
        x = "Month",
        y = "Total Count",
      ) +
      theme_minimal()
    
  } else if (input$time_units == "day") {
    daily_trends_df <- filtered_df |> 
      group_by(day) |> 
      summarise(total_count = sum(count, na.rm = TRUE), .groups = "drop")
    
    plot <- ggplot(daily_trends_df, aes(x = day, y = total_count)) +
      geom_line(color = "green", size = 1) +
      labs(
        title = "Daily Trends in Total Individuals",
        x = "Day",
        y = "Total Count"
      ) +
      theme_minimal()
  }
  
  ggplotly(plot)
})


```

Column {data-width=350}
-----------------------------------------------------------------------

### Hospital Locations in NYC

```{r}
renderLeaflet({
  filtered_data <- hospital_data |> 
    filter(Borough %in% input$boroughs)


  leaflet(filtered_data) |> 
    addProviderTiles("CartoDB.Positron") |> 
    addCircleMarkers(
      lat = ~latitude,
      lng = ~longitude,
      radius = 6,
      color = ~case_when(
        Borough == "Manhattan" ~ "blue",
        Borough == "Queens" ~ "green",
        Borough == "Brooklyn" ~ "purple",
        Borough == "Bronx" ~ "red",
        Borough == "Staten Island" ~ "orange",
        TRUE ~ "gray"
      ),
      stroke = FALSE,
      fillOpacity = 0.7,
      popup = ~paste(
        "<b>Facility Name:</b> ", facility_name, "<br>",
        "<b>Facility Type:</b> ", facility_type, "<br>",
        "<b>Borough:</b> ", Borough, "<br>",
        "<b>Phone:</b> ", Phone
      ),
      group = ~Borough
    ) |> 
    addLayersControl(
      overlayGroups = c("Manhattan", "Queens", "Brooklyn", "Bronx", "Staten Island"),
      options = layersControlOptions(collapsed = FALSE)
    ) |> 
    setView(lng = -73.935242, lat = 40.730610, zoom = 10)
})

```



